### ISSUE TITLE
라이센스가 어케 되나요?

### ISSUE THREAD

**Issue by darksoldier1404** [outstanding1301/donation-alert-api#2]
당장은 제 DPP-Core쪽에 사용중입니다만
DPP-Core는 Mit 라이센스입니다.

일..단 미리 적용시키기는 했는데
혹시라도 나중에 문제 생기면 안되기때문에 미리 질문드립니다 ;)

**Comment by outstanding1301** [comment]
MIT 라이센스입니다. 자유롭게 쓰셔도 좋습니다.
